Update to v2.7.0
imodeljs/imodeljs-samples pull request #36
Opened 2020-10-05 16:52 UTC by williamkbentley

2020-10-06 20:28 UTC, calebmshafer requested changes
Few comments based no the new recommended settings for Electron.

2020-10-06 20:28 UTC, calebmshafer commented on .vscode/launch.json
> +        "ITWIN_VIEWER_SNAPSHOT": "tpb.ibim"
Let's leave the iModel empty here or remove this line entirely.

2020-10-06 20:28 UTC, calebmshafer commented on .vscode/launch.json
> +      "name": "[BACKEND] simple-viewer-app electron",
We should probably make the same changes for the Ninezone app as well.

2020-10-06 20:28 UTC, calebmshafer commented on interactive-app/ninezone-sample-app/src/backend/electronmain.ts
> +    webPreferences: {
The recommendation is to now remove both of these webPreferences when starting an Electron app.

2020-10-06 20:28 UTC, calebmshafer commented on interactive-app/simple-viewer-app/src/backend/electronmain.ts
> +    webPreferences: {
Remove here too.

2020-10-07 17:51 UTC, williamkbentley commented on interactive-app/simple-viewer-app/src/backend/electronmain.ts
> +    webPreferences: {
done

2020-10-07 18:24 UTC, calebmshafer approved these changes
LGTM

2020-10-07 18:48 UTC, merged